# Generated by Django 4.2.6 on 2024-04-13 11:07

import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('image_handle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecheck',
            name='check_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 11, 6, 56, 881387, tzinfo=datetime.timezone.utc), verbose_name='检测时间'),
        ),
    ]
